#!/usr/bin/env python3
"""Convert moon-phase SVGs to a PROGMEM RGB565 header for TFT_eSPI."""

import io, sys
import cairosvg
from PIL import Image

SIZE = 162  # pixels square

# SVG filename stem → C identifier & API moonPhase key
PHASES = [
    ("moon-new",             "MOON_NEW",             "NEW_MOON"),
    ("moon-waxing-crescent", "MOON_WAXING_CRESCENT", "WAXING_CRESCENT"),
    ("moon-first-quarter",   "MOON_FIRST_QUARTER",   "FIRST_QUARTER"),
    ("moon-waxing-gibbous",  "MOON_WAXING_GIBBOUS",  "WAXING_GIBBOUS"),
    ("moon-full",            "MOON_FULL",             "FULL_MOON"),
    ("moon-waning-gibbous",  "MOON_WANING_GIBBOUS",  "WANING_GIBBOUS"),
    ("moon-last-quarter",    "MOON_LAST_QUARTER",     "LAST_QUARTER"),
    ("moon-waning-crescent", "MOON_WANING_CRESCENT",  "WANING_CRESCENT"),
]

SRC_DIR = "/Users/stephanefrechette/Downloads"
OUT     = "/Users/stephanefrechette/Documents/PlatformIO/Projects/astro-micro-station/include/moon_icons.h"

CHROMA = 0xFFFF  # transparent sentinel

def to_grey_rgb565(r, g, b, a):
    """Desaturate to luminance then alpha-blend with black background."""
    lum = int(0.299 * r + 0.587 * g + 0.114 * b)
    out = lum * a // 255   # composite onto black
    return out

lines = []
lines.append("// Auto-generated by svg_to_h.py — do not edit by hand")
lines.append("#pragma once")
lines.append("#include <Arduino.h>")
lines.append("")
lines.append(f"static constexpr int MOON_IMG_W = {SIZE};")
lines.append(f"static constexpr int MOON_IMG_H = {SIZE};")
lines.append("")

identifiers = []

for stem, ident, key in PHASES:
    svg_path = f"{SRC_DIR}/{stem}.svg"
    print(f"  converting {stem}.svg ...", end=" ", flush=True)

    png_data = cairosvg.svg2png(url=svg_path, output_width=SIZE, output_height=SIZE)
    img = Image.open(io.BytesIO(png_data)).convert("RGBA")

    pixels = []
    for py in range(SIZE):
        for px in range(SIZE):
            r, g, b, a = img.getpixel((px, py))
            grey = to_grey_rgb565(r, g, b, a)
            if grey < 4:
                # nearly transparent/black — skip drawing (matches black bg)
                pixels.append(CHROMA)
            else:
                c = ((grey & 0xF8) << 8) | ((grey & 0xFC) << 3) | (grey >> 3)
                if c == CHROMA:
                    c = 0xFFFE  # avoid chroma collision
                pixels.append(c)

    lines.append(f"static const uint16_t {ident}[{SIZE*SIZE}] PROGMEM = {{")
    row_size = SIZE  # one source row per output line
    for i in range(0, len(pixels), row_size):
        chunk = pixels[i:i+row_size]
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    identifiers.append((ident, key))
    print(f"done ({SIZE*SIZE} pixels)")

# Lookup table: index matches PHASES order
lines.append("// moonPhaseIndex(raw) returns 0-7 matching the arrays above")
lines.append("inline int moonPhaseIndex(const String& raw) {")
for i, (ident, key) in enumerate(identifiers):
    lines.append(f'    if (raw == "{key}") return {i};')
lines.append("    return 0;  // default to new moon")
lines.append("}")
lines.append("")

# Pointer array for O(1) lookup
lines.append("static const uint16_t* MOON_IMGS[] = {")
for ident, key in identifiers:
    lines.append(f"    {ident},")
lines.append("};")
lines.append("")

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"\nWrote {OUT}")
total_kb = len(PHASES) * SIZE * SIZE * 2 / 1024
print(f"Total flash: {total_kb:.0f} KB for {len(PHASES)} images")
